#!/usr/bin/env python3
"""Generate our third-party tap formula from the exact release archive that was verified."""

import argparse
import json
from pathlib import Path

from release_artifact import check_checksum, inspect_archive


def formula_for(release, url):
    if release["architecture"] != "arm64":
        raise ValueError("The first Homebrew distribution supports the verified Apple Silicon build only")
    # JSON quoting is also safe for these Ruby strings; reject Ruby interpolation separately.
    if "#" in url:
        raise ValueError("Archive URL must not contain Ruby interpolation")
    return '''# Generated by AgentSoma's release workflow; do not edit version or checksum independently.
require "digest"
require "json"

class Agentsoma < Formula
  desc "Eyes and hands for agents operating a real iPhone"
  homepage "https://github.com/HughLee824/AgentSoma"
  url %s
  version %s
  sha256 %s
  license "MIT"

  depends_on arch: :arm64
  depends_on macos: :sequoia

  # The signed CLI and Runner manifest must remain byte-for-byte paired.
  skip_clean "libexec"

  def install
    libexec.install "bin", "libexec"
    bin.install_symlink libexec/"bin/agentsoma"
    prefix.install "README.md", "LICENSE", "build-info.json"
    (pkgshare/"licenses").install "licenses/SwiftArgumentParser.txt"
  end

  def caveats
    <<~EOS
      Prepare an iPhone with: agentsoma setup --device <UDID>
      Device setup requires full Xcode and your own Apple development signing.
      Install and upgrade do not compile or sign the Runner, or access your iPhone.
      After an upgrade, disconnect old sessions and rerun setup if requested.
    EOS
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/agentsoma --version").strip
    runner = libexec/"libexec/agentsoma/runner"
    manifest = JSON.parse((runner/"manifest.json").read)
    assert_equal version.to_s, manifest.fetch("releaseVersion")
    assert_equal manifest.fetch("cliSHA256"), Digest::SHA256.file(libexec/"bin/agentsoma").hexdigest
    manifest.fetch("files").each do |name, expected|
      assert_equal expected, Digest::SHA256.file(runner/name).hexdigest, "Changed Runner file: #{name}"
    end
  end
end
''' % (json.dumps(url), json.dumps(release["version"]), json.dumps(release["sha256"]))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("archive", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--local", action="store_true", help="Use a file URL for local brew acceptance only; never publish this formula")
    args = parser.parse_args()
    check_checksum(args.archive)
    release = inspect_archive(args.archive, require_clean=not args.local)
    url = args.archive.resolve().as_uri() if args.local else (
        f'https://github.com/HughLee824/AgentSoma/releases/download/v{release["version"]}/{args.archive.name}')
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(formula_for(release, url))
    print(args.output)


if __name__ == "__main__":
    main()
